# S&P 500 Stock List (Auto-generated)
# fields: code(티커), market(거래소), name(영문명), korean_name(한글명), sector(섹터)

US_TARGET_STOCKS = [
    {'code': 'MMM', 'market': 'NYS', 'name': "3M", 'korean_name': "3M", 'sector': 'Industrials'},
    {'code': 'AOS', 'market': 'NYS', 'name': "A. O. Smith", 'korean_name': "A. O. Smith", 'sector': 'Industrials'},
    {'code': 'ABT', 'market': 'NYS', 'name': "Abbott Laboratories", 'korean_name': "Abbott Laboratories", 'sector': 'Health Care'},
    {'code': 'ABBV', 'market': 'NAS', 'name': "AbbVie", 'korean_name': "AbbVie", 'sector': 'Health Care'},
    {'code': 'ACN', 'market': 'NYS', 'name': "Accenture", 'korean_name': "Accenture", 'sector': 'Information Technology'},
    {'code': 'ADBE', 'market': 'NAS', 'name': "Adobe Inc.", 'korean_name': "Adobe Inc.", 'sector': 'Information Technology'},
    {'code': 'AMD', 'market': 'NAS', 'name': "Advanced Micro Devices", 'korean_name': "Advanced Micro Devices", 'sector': 'Information Technology'},
    {'code': 'AES', 'market': 'NYS', 'name': "AES Corporation", 'korean_name': "AES Corporation", 'sector': 'Utilities'},
    {'code': 'AFL', 'market': 'NYS', 'name': "Aflac", 'korean_name': "Aflac", 'sector': 'Financials'},
    {'code': 'A', 'market': 'NYS', 'name': "Agilent Technologies", 'korean_name': "Agilent Technologies", 'sector': 'Health Care'},
    {'code': 'APD', 'market': 'NYS', 'name': "Air Products", 'korean_name': "Air Products", 'sector': 'Materials'},
    {'code': 'ABNB', 'market': 'NAS', 'name': "Airbnb", 'korean_name': "Airbnb", 'sector': 'Consumer Discretionary'},
    {'code': 'AKAM', 'market': 'NAS', 'name': "Akamai Technologies", 'korean_name': "Akamai Technologies", 'sector': 'Information Technology'},
    {'code': 'ALB', 'market': 'NYS', 'name': "Albemarle Corporation", 'korean_name': "Albemarle Corporation", 'sector': 'Materials'},
    {'code': 'ARE', 'market': 'NYS', 'name': "Alexandria Real Estate Equities", 'korean_name': "Alexandria Real Estate Equities", 'sector': 'Real Estate'},
    {'code': 'ALGN', 'market': 'NAS', 'name': "Align Technology", 'korean_name': "Align Technology", 'sector': 'Health Care'},
    {'code': 'ALLE', 'market': 'NAS', 'name': "Allegion", 'korean_name': "Allegion", 'sector': 'Industrials'},
    {'code': 'LNT', 'market': 'NYS', 'name': "Alliant Energy", 'korean_name': "Alliant Energy", 'sector': 'Utilities'},
    {'code': 'ALL', 'market': 'NYS', 'name': "Allstate", 'korean_name': "Allstate", 'sector': 'Financials'},
    {'code': 'GOOGL', 'market': 'NAS', 'name': "Alphabet Inc. (Class A)", 'korean_name': "Alphabet Inc. (Class A)", 'sector': 'Communication Services'},
    {'code': 'GOOG', 'market': 'NAS', 'name': "Alphabet Inc. (Class C)", 'korean_name': "Alphabet Inc. (Class C)", 'sector': 'Communication Services'},
    {'code': 'MO', 'market': 'NYS', 'name': "Altria", 'korean_name': "Altria", 'sector': 'Consumer Staples'},
    {'code': 'AMZN', 'market': 'NAS', 'name': "Amazon", 'korean_name': "Amazon", 'sector': 'Consumer Discretionary'},
    {'code': 'AMCR', 'market': 'NAS', 'name': "Amcor", 'korean_name': "Amcor", 'sector': 'Materials'},
    {'code': 'AEE', 'market': 'NYS', 'name': "Ameren", 'korean_name': "Ameren", 'sector': 'Utilities'},
    {'code': 'AEP', 'market': 'NYS', 'name': "American Electric Power", 'korean_name': "American Electric Power", 'sector': 'Utilities'},
    {'code': 'AXP', 'market': 'NYS', 'name': "American Express", 'korean_name': "American Express", 'sector': 'Financials'},
    {'code': 'AIG', 'market': 'NYS', 'name': "American International Group", 'korean_name': "American International Group", 'sector': 'Financials'},
    {'code': 'AMT', 'market': 'NYS', 'name': "American Tower", 'korean_name': "American Tower", 'sector': 'Real Estate'},
    {'code': 'AWK', 'market': 'NYS', 'name': "American Water Works", 'korean_name': "American Water Works", 'sector': 'Utilities'},
    {'code': 'AMP', 'market': 'NYS', 'name': "Ameriprise Financial", 'korean_name': "Ameriprise Financial", 'sector': 'Financials'},
    {'code': 'AME', 'market': 'NYS', 'name': "Ametek", 'korean_name': "Ametek", 'sector': 'Industrials'},
    {'code': 'AMGN', 'market': 'NAS', 'name': "Amgen", 'korean_name': "Amgen", 'sector': 'Health Care'},
    {'code': 'APH', 'market': 'NYS', 'name': "Amphenol", 'korean_name': "Amphenol", 'sector': 'Information Technology'},
    {'code': 'ADI', 'market': 'NYS', 'name': "Analog Devices", 'korean_name': "Analog Devices", 'sector': 'Information Technology'},
    {'code': 'AON', 'market': 'NYS', 'name': "Aon plc", 'korean_name': "Aon plc", 'sector': 'Financials'},
    {'code': 'APA', 'market': 'NYS', 'name': "APA Corporation", 'korean_name': "APA Corporation", 'sector': 'Energy'},
    {'code': 'APO', 'market': 'NYS', 'name': "Apollo Global Management", 'korean_name': "Apollo Global Management", 'sector': 'Financials'},
    {'code': 'AAPL', 'market': 'NAS', 'name': "Apple Inc.", 'korean_name': "Apple Inc.", 'sector': 'Information Technology'},
    {'code': 'AMAT', 'market': 'NAS', 'name': "Applied Materials", 'korean_name': "Applied Materials", 'sector': 'Information Technology'},
    {'code': 'APP', 'market': 'NYS', 'name': "AppLovin", 'korean_name': "AppLovin", 'sector': 'Information Technology'},
    {'code': 'APTV', 'market': 'NAS', 'name': "Aptiv", 'korean_name': "Aptiv", 'sector': 'Consumer Discretionary'},
    {'code': 'ACGL', 'market': 'NAS', 'name': "Arch Capital Group", 'korean_name': "Arch Capital Group", 'sector': 'Financials'},
    {'code': 'ADM', 'market': 'NYS', 'name': "Archer Daniels Midland", 'korean_name': "Archer Daniels Midland", 'sector': 'Consumer Staples'},
    {'code': 'ARES', 'market': 'NAS', 'name': "Ares Management", 'korean_name': "Ares Management", 'sector': 'Financials'},
    {'code': 'ANET', 'market': 'NAS', 'name': "Arista Networks", 'korean_name': "Arista Networks", 'sector': 'Information Technology'},
    {'code': 'AJG', 'market': 'NYS', 'name': "Arthur J. Gallagher & Co.", 'korean_name': "Arthur J. Gallagher & Co.", 'sector': 'Financials'},
    {'code': 'AIZ', 'market': 'NYS', 'name': "Assurant", 'korean_name': "Assurant", 'sector': 'Financials'},
    {'code': 'T', 'market': 'NYS', 'name': "AT&T", 'korean_name': "AT&T", 'sector': 'Communication Services'},
    {'code': 'ATO', 'market': 'NYS', 'name': "Atmos Energy", 'korean_name': "Atmos Energy", 'sector': 'Utilities'},
    {'code': 'ADSK', 'market': 'NAS', 'name': "Autodesk", 'korean_name': "Autodesk", 'sector': 'Information Technology'},
    {'code': 'ADP', 'market': 'NYS', 'name': "Automatic Data Processing", 'korean_name': "Automatic Data Processing", 'sector': 'Industrials'},
    {'code': 'AZO', 'market': 'NYS', 'name': "AutoZone", 'korean_name': "AutoZone", 'sector': 'Consumer Discretionary'},
    {'code': 'AVB', 'market': 'NYS', 'name': "AvalonBay Communities", 'korean_name': "AvalonBay Communities", 'sector': 'Real Estate'},
    {'code': 'AVY', 'market': 'NYS', 'name': "Avery Dennison", 'korean_name': "Avery Dennison", 'sector': 'Materials'},
    {'code': 'AXON', 'market': 'NAS', 'name': "Axon Enterprise", 'korean_name': "Axon Enterprise", 'sector': 'Industrials'},
    {'code': 'BKR', 'market': 'NYS', 'name': "Baker Hughes", 'korean_name': "Baker Hughes", 'sector': 'Energy'},
    {'code': 'BALL', 'market': 'NAS', 'name': "Ball Corporation", 'korean_name': "Ball Corporation", 'sector': 'Materials'},
    {'code': 'BAC', 'market': 'NYS', 'name': "Bank of America", 'korean_name': "Bank of America", 'sector': 'Financials'},
    {'code': 'BAX', 'market': 'NYS', 'name': "Baxter International", 'korean_name': "Baxter International", 'sector': 'Health Care'},
    {'code': 'BDX', 'market': 'NYS', 'name': "Becton Dickinson", 'korean_name': "Becton Dickinson", 'sector': 'Health Care'},
    {'code': 'BRK.B', 'market': 'NYS', 'name': "Berkshire Hathaway", 'korean_name': "Berkshire Hathaway", 'sector': 'Financials'},
    {'code': 'BBY', 'market': 'NYS', 'name': "Best Buy", 'korean_name': "Best Buy", 'sector': 'Consumer Discretionary'},
    {'code': 'TECH', 'market': 'NAS', 'name': "Bio-Techne", 'korean_name': "Bio-Techne", 'sector': 'Health Care'},
    {'code': 'BIIB', 'market': 'NAS', 'name': "Biogen", 'korean_name': "Biogen", 'sector': 'Health Care'},
    {'code': 'BLK', 'market': 'NYS', 'name': "BlackRock", 'korean_name': "BlackRock", 'sector': 'Financials'},
    {'code': 'BX', 'market': 'NYS', 'name': "Blackstone Inc.", 'korean_name': "Blackstone Inc.", 'sector': 'Financials'},
    {'code': 'XYZ', 'market': 'NYS', 'name': "Block, Inc.", 'korean_name': "Block, Inc.", 'sector': 'Financials'},
    {'code': 'BK', 'market': 'NYS', 'name': "BNY Mellon", 'korean_name': "BNY Mellon", 'sector': 'Financials'},
    {'code': 'BA', 'market': 'NYS', 'name': "Boeing", 'korean_name': "Boeing", 'sector': 'Industrials'},
    {'code': 'BKNG', 'market': 'NAS', 'name': "Booking Holdings", 'korean_name': "Booking Holdings", 'sector': 'Consumer Discretionary'},
    {'code': 'BSX', 'market': 'NYS', 'name': "Boston Scientific", 'korean_name': "Boston Scientific", 'sector': 'Health Care'},
    {'code': 'BMY', 'market': 'NYS', 'name': "Bristol Myers Squibb", 'korean_name': "Bristol Myers Squibb", 'sector': 'Health Care'},
    {'code': 'AVGO', 'market': 'NAS', 'name': "Broadcom", 'korean_name': "Broadcom", 'sector': 'Information Technology'},
    {'code': 'BR', 'market': 'NYS', 'name': "Broadridge Financial Solutions", 'korean_name': "Broadridge Financial Solutions", 'sector': 'Industrials'},
    {'code': 'BRO', 'market': 'NYS', 'name': "Brown & Brown", 'korean_name': "Brown & Brown", 'sector': 'Financials'},
    {'code': 'BF.B', 'market': 'NAS', 'name': "Brown–Forman", 'korean_name': "Brown–Forman", 'sector': 'Consumer Staples'},
    {'code': 'BLDR', 'market': 'NAS', 'name': "Builders FirstSource", 'korean_name': "Builders FirstSource", 'sector': 'Industrials'},
    {'code': 'BG', 'market': 'NYS', 'name': "Bunge Global", 'korean_name': "Bunge Global", 'sector': 'Consumer Staples'},
    {'code': 'BXP', 'market': 'NYS', 'name': "BXP, Inc.", 'korean_name': "BXP, Inc.", 'sector': 'Real Estate'},
    {'code': 'CHRW', 'market': 'NAS', 'name': "C.H. Robinson", 'korean_name': "C.H. Robinson", 'sector': 'Industrials'},
    {'code': 'CDNS', 'market': 'NAS', 'name': "Cadence Design Systems", 'korean_name': "Cadence Design Systems", 'sector': 'Information Technology'},
    {'code': 'CPT', 'market': 'NYS', 'name': "Camden Property Trust", 'korean_name': "Camden Property Trust", 'sector': 'Real Estate'},
    {'code': 'CPB', 'market': 'NYS', 'name': "Campbell's Company (The)", 'korean_name': "Campbell's Company (The)", 'sector': 'Consumer Staples'},
    {'code': 'COF', 'market': 'NYS', 'name': "Capital One", 'korean_name': "Capital One", 'sector': 'Financials'},
    {'code': 'CAH', 'market': 'NYS', 'name': "Cardinal Health", 'korean_name': "Cardinal Health", 'sector': 'Health Care'},
    {'code': 'CCL', 'market': 'NYS', 'name': "Carnival", 'korean_name': "Carnival", 'sector': 'Consumer Discretionary'},
    {'code': 'CARR', 'market': 'NAS', 'name': "Carrier Global", 'korean_name': "Carrier Global", 'sector': 'Industrials'},
    {'code': 'CVNA', 'market': 'NAS', 'name': "Carvana", 'korean_name': "Carvana", 'sector': 'Consumer Discretionary'},
    {'code': 'CAT', 'market': 'NYS', 'name': "Caterpillar Inc.", 'korean_name': "Caterpillar Inc.", 'sector': 'Industrials'},
    {'code': 'CBOE', 'market': 'NAS', 'name': "Cboe Global Markets", 'korean_name': "Cboe Global Markets", 'sector': 'Financials'},
    {'code': 'CBRE', 'market': 'NAS', 'name': "CBRE Group", 'korean_name': "CBRE Group", 'sector': 'Real Estate'},
    {'code': 'CDW', 'market': 'NYS', 'name': "CDW Corporation", 'korean_name': "CDW Corporation", 'sector': 'Information Technology'},
    {'code': 'COR', 'market': 'NYS', 'name': "Cencora", 'korean_name': "Cencora", 'sector': 'Health Care'},
    {'code': 'CNC', 'market': 'NYS', 'name': "Centene Corporation", 'korean_name': "Centene Corporation", 'sector': 'Health Care'},
    {'code': 'CNP', 'market': 'NYS', 'name': "CenterPoint Energy", 'korean_name': "CenterPoint Energy", 'sector': 'Utilities'},
    {'code': 'CF', 'market': 'NYS', 'name': "CF Industries", 'korean_name': "CF Industries", 'sector': 'Materials'},
    {'code': 'CRL', 'market': 'NYS', 'name': "Charles River Laboratories", 'korean_name': "Charles River Laboratories", 'sector': 'Health Care'},
    {'code': 'SCHW', 'market': 'NAS', 'name': "Charles Schwab Corporation", 'korean_name': "Charles Schwab Corporation", 'sector': 'Financials'},
    {'code': 'CHTR', 'market': 'NAS', 'name': "Charter Communications", 'korean_name': "Charter Communications", 'sector': 'Communication Services'},
    {'code': 'CVX', 'market': 'NYS', 'name': "Chevron Corporation", 'korean_name': "Chevron Corporation", 'sector': 'Energy'},
    {'code': 'CMG', 'market': 'NYS', 'name': "Chipotle Mexican Grill", 'korean_name': "Chipotle Mexican Grill", 'sector': 'Consumer Discretionary'},
    {'code': 'CB', 'market': 'NYS', 'name': "Chubb Limited", 'korean_name': "Chubb Limited", 'sector': 'Financials'},
    {'code': 'CHD', 'market': 'NYS', 'name': "Church & Dwight", 'korean_name': "Church & Dwight", 'sector': 'Consumer Staples'},
    {'code': 'CIEN', 'market': 'NAS', 'name': "Ciena", 'korean_name': "Ciena", 'sector': 'Information Technology'},
    {'code': 'CI', 'market': 'NYS', 'name': "Cigna", 'korean_name': "Cigna", 'sector': 'Health Care'},
    {'code': 'CINF', 'market': 'NAS', 'name': "Cincinnati Financial", 'korean_name': "Cincinnati Financial", 'sector': 'Financials'},
    {'code': 'CTAS', 'market': 'NAS', 'name': "Cintas", 'korean_name': "Cintas", 'sector': 'Industrials'},
    {'code': 'CSCO', 'market': 'NAS', 'name': "Cisco", 'korean_name': "Cisco", 'sector': 'Information Technology'},
    {'code': 'C', 'market': 'NYS', 'name': "Citigroup", 'korean_name': "Citigroup", 'sector': 'Financials'},
    {'code': 'CFG', 'market': 'NYS', 'name': "Citizens Financial Group", 'korean_name': "Citizens Financial Group", 'sector': 'Financials'},
    {'code': 'CLX', 'market': 'NYS', 'name': "Clorox", 'korean_name': "Clorox", 'sector': 'Consumer Staples'},
    {'code': 'CME', 'market': 'NYS', 'name': "CME Group", 'korean_name': "CME Group", 'sector': 'Financials'},
    {'code': 'CMS', 'market': 'NYS', 'name': "CMS Energy", 'korean_name': "CMS Energy", 'sector': 'Utilities'},
    {'code': 'KO', 'market': 'NYS', 'name': "Coca-Cola Company (The)", 'korean_name': "Coca-Cola Company (The)", 'sector': 'Consumer Staples'},
    {'code': 'CTSH', 'market': 'NAS', 'name': "Cognizant", 'korean_name': "Cognizant", 'sector': 'Information Technology'},
    {'code': 'COIN', 'market': 'NAS', 'name': "Coinbase", 'korean_name': "Coinbase", 'sector': 'Financials'},
    {'code': 'CL', 'market': 'NYS', 'name': "Colgate-Palmolive", 'korean_name': "Colgate-Palmolive", 'sector': 'Consumer Staples'},
    {'code': 'CMCSA', 'market': 'NAS', 'name': "Comcast", 'korean_name': "Comcast", 'sector': 'Communication Services'},
    {'code': 'FIX', 'market': 'NYS', 'name': "Comfort Systems USA", 'korean_name': "Comfort Systems USA", 'sector': 'Industrials'},
    {'code': 'CAG', 'market': 'NYS', 'name': "Conagra Brands", 'korean_name': "Conagra Brands", 'sector': 'Consumer Staples'},
    {'code': 'COP', 'market': 'NYS', 'name': "ConocoPhillips", 'korean_name': "ConocoPhillips", 'sector': 'Energy'},
    {'code': 'ED', 'market': 'NYS', 'name': "Consolidated Edison", 'korean_name': "Consolidated Edison", 'sector': 'Utilities'},
    {'code': 'STZ', 'market': 'NYS', 'name': "Constellation Brands", 'korean_name': "Constellation Brands", 'sector': 'Consumer Staples'},
    {'code': 'CEG', 'market': 'NYS', 'name': "Constellation Energy", 'korean_name': "Constellation Energy", 'sector': 'Utilities'},
    {'code': 'COO', 'market': 'NYS', 'name': "Cooper Companies (The)", 'korean_name': "Cooper Companies (The)", 'sector': 'Health Care'},
    {'code': 'CPRT', 'market': 'NAS', 'name': "Copart", 'korean_name': "Copart", 'sector': 'Industrials'},
    {'code': 'GLW', 'market': 'NYS', 'name': "Corning Inc.", 'korean_name': "Corning Inc.", 'sector': 'Information Technology'},
    {'code': 'CPAY', 'market': 'NAS', 'name': "Corpay", 'korean_name': "Corpay", 'sector': 'Financials'},
    {'code': 'CTVA', 'market': 'NAS', 'name': "Corteva", 'korean_name': "Corteva", 'sector': 'Materials'},
    {'code': 'CSGP', 'market': 'NAS', 'name': "CoStar Group", 'korean_name': "CoStar Group", 'sector': 'Real Estate'},
    {'code': 'COST', 'market': 'NAS', 'name': "Costco", 'korean_name': "Costco", 'sector': 'Consumer Staples'},
    {'code': 'CTRA', 'market': 'NAS', 'name': "Coterra", 'korean_name': "Coterra", 'sector': 'Energy'},
    {'code': 'CRH', 'market': 'NYS', 'name': "CRH plc", 'korean_name': "CRH plc", 'sector': 'Materials'},
    {'code': 'CRWD', 'market': 'NAS', 'name': "CrowdStrike", 'korean_name': "CrowdStrike", 'sector': 'Information Technology'},
    {'code': 'CCI', 'market': 'NYS', 'name': "Crown Castle", 'korean_name': "Crown Castle", 'sector': 'Real Estate'},
    {'code': 'CSX', 'market': 'NYS', 'name': "CSX Corporation", 'korean_name': "CSX Corporation", 'sector': 'Industrials'},
    {'code': 'CMI', 'market': 'NYS', 'name': "Cummins", 'korean_name': "Cummins", 'sector': 'Industrials'},
    {'code': 'CVS', 'market': 'NYS', 'name': "CVS Health", 'korean_name': "CVS Health", 'sector': 'Health Care'},
    {'code': 'DHR', 'market': 'NYS', 'name': "Danaher Corporation", 'korean_name': "Danaher Corporation", 'sector': 'Health Care'},
    {'code': 'DRI', 'market': 'NYS', 'name': "Darden Restaurants", 'korean_name': "Darden Restaurants", 'sector': 'Consumer Discretionary'},
    {'code': 'DDOG', 'market': 'NAS', 'name': "Datadog", 'korean_name': "Datadog", 'sector': 'Information Technology'},
    {'code': 'DVA', 'market': 'NYS', 'name': "DaVita", 'korean_name': "DaVita", 'sector': 'Health Care'},
    {'code': 'DECK', 'market': 'NAS', 'name': "Deckers Brands", 'korean_name': "Deckers Brands", 'sector': 'Consumer Discretionary'},
    {'code': 'DE', 'market': 'NYS', 'name': "Deere & Company", 'korean_name': "Deere & Company", 'sector': 'Industrials'},
    {'code': 'DELL', 'market': 'NAS', 'name': "Dell Technologies", 'korean_name': "Dell Technologies", 'sector': 'Information Technology'},
    {'code': 'DAL', 'market': 'NYS', 'name': "Delta Air Lines", 'korean_name': "Delta Air Lines", 'sector': 'Industrials'},
    {'code': 'DVN', 'market': 'NYS', 'name': "Devon Energy", 'korean_name': "Devon Energy", 'sector': 'Energy'},
    {'code': 'DXCM', 'market': 'NAS', 'name': "Dexcom", 'korean_name': "Dexcom", 'sector': 'Health Care'},
    {'code': 'FANG', 'market': 'NAS', 'name': "Diamondback Energy", 'korean_name': "Diamondback Energy", 'sector': 'Energy'},
    {'code': 'DLR', 'market': 'NYS', 'name': "Digital Realty", 'korean_name': "Digital Realty", 'sector': 'Real Estate'},
    {'code': 'DG', 'market': 'NYS', 'name': "Dollar General", 'korean_name': "Dollar General", 'sector': 'Consumer Staples'},
    {'code': 'DLTR', 'market': 'NAS', 'name': "Dollar Tree", 'korean_name': "Dollar Tree", 'sector': 'Consumer Staples'},
    {'code': 'D', 'market': 'NYS', 'name': "Dominion Energy", 'korean_name': "Dominion Energy", 'sector': 'Utilities'},
    {'code': 'DPZ', 'market': 'NYS', 'name': "Domino's", 'korean_name': "Domino's", 'sector': 'Consumer Discretionary'},
    {'code': 'DASH', 'market': 'NAS', 'name': "DoorDash", 'korean_name': "DoorDash", 'sector': 'Consumer Discretionary'},
    {'code': 'DOV', 'market': 'NYS', 'name': "Dover Corporation", 'korean_name': "Dover Corporation", 'sector': 'Industrials'},
    {'code': 'DOW', 'market': 'NYS', 'name': "Dow Inc.", 'korean_name': "Dow Inc.", 'sector': 'Materials'},
    {'code': 'DHI', 'market': 'NYS', 'name': "D. R. Horton", 'korean_name': "D. R. Horton", 'sector': 'Consumer Discretionary'},
    {'code': 'DTE', 'market': 'NYS', 'name': "DTE Energy", 'korean_name': "DTE Energy", 'sector': 'Utilities'},
    {'code': 'DUK', 'market': 'NYS', 'name': "Duke Energy", 'korean_name': "Duke Energy", 'sector': 'Utilities'},
    {'code': 'DD', 'market': 'NYS', 'name': "DuPont", 'korean_name': "DuPont", 'sector': 'Materials'},
    {'code': 'ETN', 'market': 'NYS', 'name': "Eaton Corporation", 'korean_name': "Eaton Corporation", 'sector': 'Industrials'},
    {'code': 'EBAY', 'market': 'NAS', 'name': "eBay Inc.", 'korean_name': "eBay Inc.", 'sector': 'Consumer Discretionary'},
    {'code': 'ECL', 'market': 'NYS', 'name': "Ecolab", 'korean_name': "Ecolab", 'sector': 'Materials'},
    {'code': 'EIX', 'market': 'NYS', 'name': "Edison International", 'korean_name': "Edison International", 'sector': 'Utilities'},
    {'code': 'EW', 'market': 'NYS', 'name': "Edwards Lifesciences", 'korean_name': "Edwards Lifesciences", 'sector': 'Health Care'},
    {'code': 'EA', 'market': 'NYS', 'name': "Electronic Arts", 'korean_name': "Electronic Arts", 'sector': 'Communication Services'},
    {'code': 'ELV', 'market': 'NYS', 'name': "Elevance Health", 'korean_name': "Elevance Health", 'sector': 'Health Care'},
    {'code': 'EME', 'market': 'NYS', 'name': "Emcor", 'korean_name': "Emcor", 'sector': 'Industrials'},
    {'code': 'EMR', 'market': 'NYS', 'name': "Emerson Electric", 'korean_name': "Emerson Electric", 'sector': 'Industrials'},
    {'code': 'ETR', 'market': 'NYS', 'name': "Entergy", 'korean_name': "Entergy", 'sector': 'Utilities'},
    {'code': 'EOG', 'market': 'NYS', 'name': "EOG Resources", 'korean_name': "EOG Resources", 'sector': 'Energy'},
    {'code': 'EPAM', 'market': 'NAS', 'name': "EPAM Systems", 'korean_name': "EPAM Systems", 'sector': 'Information Technology'},
    {'code': 'EQT', 'market': 'NYS', 'name': "EQT Corporation", 'korean_name': "EQT Corporation", 'sector': 'Energy'},
    {'code': 'EFX', 'market': 'NYS', 'name': "Equifax", 'korean_name': "Equifax", 'sector': 'Industrials'},
    {'code': 'EQIX', 'market': 'NAS', 'name': "Equinix", 'korean_name': "Equinix", 'sector': 'Real Estate'},
    {'code': 'EQR', 'market': 'NYS', 'name': "Equity Residential", 'korean_name': "Equity Residential", 'sector': 'Real Estate'},
    {'code': 'ERIE', 'market': 'NAS', 'name': "Erie Indemnity", 'korean_name': "Erie Indemnity", 'sector': 'Financials'},
    {'code': 'ESS', 'market': 'NYS', 'name': "Essex Property Trust", 'korean_name': "Essex Property Trust", 'sector': 'Real Estate'},
    {'code': 'EL', 'market': 'NYS', 'name': "Estée Lauder Companies (The)", 'korean_name': "Estée Lauder Companies (The)", 'sector': 'Consumer Staples'},
    {'code': 'EG', 'market': 'NYS', 'name': "Everest Group", 'korean_name': "Everest Group", 'sector': 'Financials'},
    {'code': 'EVRG', 'market': 'NAS', 'name': "Evergy", 'korean_name': "Evergy", 'sector': 'Utilities'},
    {'code': 'ES', 'market': 'NYS', 'name': "Eversource Energy", 'korean_name': "Eversource Energy", 'sector': 'Utilities'},
    {'code': 'EXC', 'market': 'NYS', 'name': "Exelon", 'korean_name': "Exelon", 'sector': 'Utilities'},
    {'code': 'EXE', 'market': 'NYS', 'name': "Expand Energy", 'korean_name': "Expand Energy", 'sector': 'Energy'},
    {'code': 'EXPE', 'market': 'NAS', 'name': "Expedia Group", 'korean_name': "Expedia Group", 'sector': 'Consumer Discretionary'},
    {'code': 'EXPD', 'market': 'NAS', 'name': "Expeditors International", 'korean_name': "Expeditors International", 'sector': 'Industrials'},
    {'code': 'EXR', 'market': 'NYS', 'name': "Extra Space Storage", 'korean_name': "Extra Space Storage", 'sector': 'Real Estate'},
    {'code': 'XOM', 'market': 'NYS', 'name': "ExxonMobil", 'korean_name': "ExxonMobil", 'sector': 'Energy'},
    {'code': 'FFIV', 'market': 'NAS', 'name': "F5, Inc.", 'korean_name': "F5, Inc.", 'sector': 'Information Technology'},
    {'code': 'FDS', 'market': 'NYS', 'name': "FactSet", 'korean_name': "FactSet", 'sector': 'Financials'},
    {'code': 'FICO', 'market': 'NAS', 'name': "Fair Isaac", 'korean_name': "Fair Isaac", 'sector': 'Information Technology'},
    {'code': 'FAST', 'market': 'NAS', 'name': "Fastenal", 'korean_name': "Fastenal", 'sector': 'Industrials'},
    {'code': 'FRT', 'market': 'NYS', 'name': "Federal Realty Investment Trust", 'korean_name': "Federal Realty Investment Trust", 'sector': 'Real Estate'},
    {'code': 'FDX', 'market': 'NYS', 'name': "FedEx", 'korean_name': "FedEx", 'sector': 'Industrials'},
    {'code': 'FIS', 'market': 'NYS', 'name': "Fidelity National Information Services", 'korean_name': "Fidelity National Information Services", 'sector': 'Financials'},
    {'code': 'FITB', 'market': 'NAS', 'name': "Fifth Third Bancorp", 'korean_name': "Fifth Third Bancorp", 'sector': 'Financials'},
    {'code': 'FSLR', 'market': 'NAS', 'name': "First Solar", 'korean_name': "First Solar", 'sector': 'Information Technology'},
    {'code': 'FE', 'market': 'NYS', 'name': "FirstEnergy", 'korean_name': "FirstEnergy", 'sector': 'Utilities'},
    {'code': 'FISV', 'market': 'NAS', 'name': "Fiserv", 'korean_name': "Fiserv", 'sector': 'Financials'},
    {'code': 'F', 'market': 'NYS', 'name': "Ford Motor Company", 'korean_name': "Ford Motor Company", 'sector': 'Consumer Discretionary'},
    {'code': 'FTNT', 'market': 'NAS', 'name': "Fortinet", 'korean_name': "Fortinet", 'sector': 'Information Technology'},
    {'code': 'FTV', 'market': 'NYS', 'name': "Fortive", 'korean_name': "Fortive", 'sector': 'Industrials'},
    {'code': 'FOXA', 'market': 'NAS', 'name': "Fox Corporation (Class A)", 'korean_name': "Fox Corporation (Class A)", 'sector': 'Communication Services'},
    {'code': 'FOX', 'market': 'NYS', 'name': "Fox Corporation (Class B)", 'korean_name': "Fox Corporation (Class B)", 'sector': 'Communication Services'},
    {'code': 'BEN', 'market': 'NYS', 'name': "Franklin Resources", 'korean_name': "Franklin Resources", 'sector': 'Financials'},
    {'code': 'FCX', 'market': 'NYS', 'name': "Freeport-McMoRan", 'korean_name': "Freeport-McMoRan", 'sector': 'Materials'},
    {'code': 'GRMN', 'market': 'NAS', 'name': "Garmin", 'korean_name': "Garmin", 'sector': 'Consumer Discretionary'},
    {'code': 'IT', 'market': 'NYS', 'name': "Gartner", 'korean_name': "Gartner", 'sector': 'Information Technology'},
    {'code': 'GE', 'market': 'NYS', 'name': "GE Aerospace", 'korean_name': "GE Aerospace", 'sector': 'Industrials'},
    {'code': 'GEHC', 'market': 'NAS', 'name': "GE HealthCare", 'korean_name': "GE HealthCare", 'sector': 'Health Care'},
    {'code': 'GEV', 'market': 'NYS', 'name': "GE Vernova", 'korean_name': "GE Vernova", 'sector': 'Industrials'},
    {'code': 'GEN', 'market': 'NYS', 'name': "Gen Digital", 'korean_name': "Gen Digital", 'sector': 'Information Technology'},
    {'code': 'GNRC', 'market': 'NAS', 'name': "Generac", 'korean_name': "Generac", 'sector': 'Industrials'},
    {'code': 'GD', 'market': 'NYS', 'name': "General Dynamics", 'korean_name': "General Dynamics", 'sector': 'Industrials'},
    {'code': 'GIS', 'market': 'NYS', 'name': "General Mills", 'korean_name': "General Mills", 'sector': 'Consumer Staples'},
    {'code': 'GM', 'market': 'NYS', 'name': "General Motors", 'korean_name': "General Motors", 'sector': 'Consumer Discretionary'},
    {'code': 'GPC', 'market': 'NYS', 'name': "Genuine Parts Company", 'korean_name': "Genuine Parts Company", 'sector': 'Consumer Discretionary'},
    {'code': 'GILD', 'market': 'NAS', 'name': "Gilead Sciences", 'korean_name': "Gilead Sciences", 'sector': 'Health Care'},
    {'code': 'GPN', 'market': 'NYS', 'name': "Global Payments", 'korean_name': "Global Payments", 'sector': 'Financials'},
    {'code': 'GL', 'market': 'NYS', 'name': "Globe Life", 'korean_name': "Globe Life", 'sector': 'Financials'},
    {'code': 'GDDY', 'market': 'NAS', 'name': "GoDaddy", 'korean_name': "GoDaddy", 'sector': 'Information Technology'},
    {'code': 'GS', 'market': 'NYS', 'name': "Goldman Sachs", 'korean_name': "Goldman Sachs", 'sector': 'Financials'},
    {'code': 'HAL', 'market': 'NYS', 'name': "Halliburton", 'korean_name': "Halliburton", 'sector': 'Energy'},
    {'code': 'HIG', 'market': 'NYS', 'name': "Hartford (The)", 'korean_name': "Hartford (The)", 'sector': 'Financials'},
    {'code': 'HAS', 'market': 'NYS', 'name': "Hasbro", 'korean_name': "Hasbro", 'sector': 'Consumer Discretionary'},
    {'code': 'HCA', 'market': 'NYS', 'name': "HCA Healthcare", 'korean_name': "HCA Healthcare", 'sector': 'Health Care'},
    {'code': 'DOC', 'market': 'NYS', 'name': "Healthpeak Properties", 'korean_name': "Healthpeak Properties", 'sector': 'Real Estate'},
    {'code': 'HSIC', 'market': 'NAS', 'name': "Henry Schein", 'korean_name': "Henry Schein", 'sector': 'Health Care'},
    {'code': 'HSY', 'market': 'NYS', 'name': "Hershey Company (The)", 'korean_name': "Hershey Company (The)", 'sector': 'Consumer Staples'},
    {'code': 'HPE', 'market': 'NYS', 'name': "Hewlett Packard Enterprise", 'korean_name': "Hewlett Packard Enterprise", 'sector': 'Information Technology'},
    {'code': 'HLT', 'market': 'NYS', 'name': "Hilton Worldwide", 'korean_name': "Hilton Worldwide", 'sector': 'Consumer Discretionary'},
    {'code': 'HOLX', 'market': 'NAS', 'name': "Hologic", 'korean_name': "Hologic", 'sector': 'Health Care'},
    {'code': 'HD', 'market': 'NYS', 'name': "Home Depot (The)", 'korean_name': "Home Depot (The)", 'sector': 'Consumer Discretionary'},
    {'code': 'HON', 'market': 'NYS', 'name': "Honeywell", 'korean_name': "Honeywell", 'sector': 'Industrials'},
    {'code': 'HRL', 'market': 'NYS', 'name': "Hormel Foods", 'korean_name': "Hormel Foods", 'sector': 'Consumer Staples'},
    {'code': 'HST', 'market': 'NYS', 'name': "Host Hotels & Resorts", 'korean_name': "Host Hotels & Resorts", 'sector': 'Real Estate'},
    {'code': 'HWM', 'market': 'NYS', 'name': "Howmet Aerospace", 'korean_name': "Howmet Aerospace", 'sector': 'Industrials'},
    {'code': 'HPQ', 'market': 'NYS', 'name': "HP Inc.", 'korean_name': "HP Inc.", 'sector': 'Information Technology'},
    {'code': 'HUBB', 'market': 'NAS', 'name': "Hubbell Incorporated", 'korean_name': "Hubbell Incorporated", 'sector': 'Industrials'},
    {'code': 'HUM', 'market': 'NYS', 'name': "Humana", 'korean_name': "Humana", 'sector': 'Health Care'},
    {'code': 'HBAN', 'market': 'NAS', 'name': "Huntington Bancshares", 'korean_name': "Huntington Bancshares", 'sector': 'Financials'},
    {'code': 'HII', 'market': 'NYS', 'name': "Huntington Ingalls Industries", 'korean_name': "Huntington Ingalls Industries", 'sector': 'Industrials'},
    {'code': 'IBM', 'market': 'NYS', 'name': "IBM", 'korean_name': "IBM", 'sector': 'Information Technology'},
    {'code': 'IEX', 'market': 'NYS', 'name': "IDEX Corporation", 'korean_name': "IDEX Corporation", 'sector': 'Industrials'},
    {'code': 'IDXX', 'market': 'NAS', 'name': "Idexx Laboratories", 'korean_name': "Idexx Laboratories", 'sector': 'Health Care'},
    {'code': 'ITW', 'market': 'NYS', 'name': "Illinois Tool Works", 'korean_name': "Illinois Tool Works", 'sector': 'Industrials'},
    {'code': 'INCY', 'market': 'NAS', 'name': "Incyte", 'korean_name': "Incyte", 'sector': 'Health Care'},
    {'code': 'IR', 'market': 'NYS', 'name': "Ingersoll Rand", 'korean_name': "Ingersoll Rand", 'sector': 'Industrials'},
    {'code': 'PODD', 'market': 'NAS', 'name': "Insulet Corporation", 'korean_name': "Insulet Corporation", 'sector': 'Health Care'},
    {'code': 'INTC', 'market': 'NAS', 'name': "Intel", 'korean_name': "Intel", 'sector': 'Information Technology'},
    {'code': 'IBKR', 'market': 'NAS', 'name': "Interactive Brokers", 'korean_name': "Interactive Brokers", 'sector': 'Financials'},
    {'code': 'ICE', 'market': 'NYS', 'name': "Intercontinental Exchange", 'korean_name': "Intercontinental Exchange", 'sector': 'Financials'},
    {'code': 'IFF', 'market': 'NYS', 'name': "International Flavors & Fragrances", 'korean_name': "International Flavors & Fragrances", 'sector': 'Materials'},
    {'code': 'IP', 'market': 'NYS', 'name': "International Paper", 'korean_name': "International Paper", 'sector': 'Materials'},
    {'code': 'INTU', 'market': 'NAS', 'name': "Intuit", 'korean_name': "Intuit", 'sector': 'Information Technology'},
    {'code': 'ISRG', 'market': 'NAS', 'name': "Intuitive Surgical", 'korean_name': "Intuitive Surgical", 'sector': 'Health Care'},
    {'code': 'IVZ', 'market': 'NYS', 'name': "Invesco", 'korean_name': "Invesco", 'sector': 'Financials'},
    {'code': 'INVH', 'market': 'NAS', 'name': "Invitation Homes", 'korean_name': "Invitation Homes", 'sector': 'Real Estate'},
    {'code': 'IQV', 'market': 'NYS', 'name': "IQVIA", 'korean_name': "IQVIA", 'sector': 'Health Care'},
    {'code': 'IRM', 'market': 'NYS', 'name': "Iron Mountain", 'korean_name': "Iron Mountain", 'sector': 'Real Estate'},
    {'code': 'JBHT', 'market': 'NAS', 'name': "J.B. Hunt", 'korean_name': "J.B. Hunt", 'sector': 'Industrials'},
    {'code': 'JBL', 'market': 'NYS', 'name': "Jabil", 'korean_name': "Jabil", 'sector': 'Information Technology'},
    {'code': 'JKHY', 'market': 'NAS', 'name': "Jack Henry & Associates", 'korean_name': "Jack Henry & Associates", 'sector': 'Financials'},
    {'code': 'J', 'market': 'NYS', 'name': "Jacobs Solutions", 'korean_name': "Jacobs Solutions", 'sector': 'Industrials'},
    {'code': 'JNJ', 'market': 'NYS', 'name': "Johnson & Johnson", 'korean_name': "Johnson & Johnson", 'sector': 'Health Care'},
    {'code': 'JCI', 'market': 'NYS', 'name': "Johnson Controls", 'korean_name': "Johnson Controls", 'sector': 'Industrials'},
    {'code': 'JPM', 'market': 'NYS', 'name': "JPMorgan Chase", 'korean_name': "JPMorgan Chase", 'sector': 'Financials'},
    {'code': 'KVUE', 'market': 'NAS', 'name': "Kenvue", 'korean_name': "Kenvue", 'sector': 'Consumer Staples'},
    {'code': 'KDP', 'market': 'NYS', 'name': "Keurig Dr Pepper", 'korean_name': "Keurig Dr Pepper", 'sector': 'Consumer Staples'},
    {'code': 'KEY', 'market': 'NYS', 'name': "KeyCorp", 'korean_name': "KeyCorp", 'sector': 'Financials'},
    {'code': 'KEYS', 'market': 'NAS', 'name': "Keysight Technologies", 'korean_name': "Keysight Technologies", 'sector': 'Information Technology'},
    {'code': 'KMB', 'market': 'NYS', 'name': "Kimberly-Clark", 'korean_name': "Kimberly-Clark", 'sector': 'Consumer Staples'},
    {'code': 'KIM', 'market': 'NYS', 'name': "Kimco Realty", 'korean_name': "Kimco Realty", 'sector': 'Real Estate'},
    {'code': 'KMI', 'market': 'NYS', 'name': "Kinder Morgan", 'korean_name': "Kinder Morgan", 'sector': 'Energy'},
    {'code': 'KKR', 'market': 'NYS', 'name': "KKR & Co.", 'korean_name': "KKR & Co.", 'sector': 'Financials'},
    {'code': 'KLAC', 'market': 'NAS', 'name': "KLA Corporation", 'korean_name': "KLA Corporation", 'sector': 'Information Technology'},
    {'code': 'KHC', 'market': 'NYS', 'name': "Kraft Heinz", 'korean_name': "Kraft Heinz", 'sector': 'Consumer Staples'},
    {'code': 'KR', 'market': 'NYS', 'name': "Kroger", 'korean_name': "Kroger", 'sector': 'Consumer Staples'},
    {'code': 'LHX', 'market': 'NYS', 'name': "L3Harris", 'korean_name': "L3Harris", 'sector': 'Industrials'},
    {'code': 'LH', 'market': 'NYS', 'name': "Labcorp", 'korean_name': "Labcorp", 'sector': 'Health Care'},
    {'code': 'LRCX', 'market': 'NAS', 'name': "Lam Research", 'korean_name': "Lam Research", 'sector': 'Information Technology'},
    {'code': 'LW', 'market': 'NYS', 'name': "Lamb Weston", 'korean_name': "Lamb Weston", 'sector': 'Consumer Staples'},
    {'code': 'LVS', 'market': 'NYS', 'name': "Las Vegas Sands", 'korean_name': "Las Vegas Sands", 'sector': 'Consumer Discretionary'},
    {'code': 'LDOS', 'market': 'NAS', 'name': "Leidos", 'korean_name': "Leidos", 'sector': 'Industrials'},
    {'code': 'LEN', 'market': 'NYS', 'name': "Lennar", 'korean_name': "Lennar", 'sector': 'Consumer Discretionary'},
    {'code': 'LII', 'market': 'NYS', 'name': "Lennox International", 'korean_name': "Lennox International", 'sector': 'Industrials'},
    {'code': 'LLY', 'market': 'NYS', 'name': "Lilly (Eli)", 'korean_name': "Lilly (Eli)", 'sector': 'Health Care'},
    {'code': 'LIN', 'market': 'NYS', 'name': "Linde plc", 'korean_name': "Linde plc", 'sector': 'Materials'},
    {'code': 'LYV', 'market': 'NYS', 'name': "Live Nation Entertainment", 'korean_name': "Live Nation Entertainment", 'sector': 'Communication Services'},
    {'code': 'LMT', 'market': 'NYS', 'name': "Lockheed Martin", 'korean_name': "Lockheed Martin", 'sector': 'Industrials'},
    {'code': 'L', 'market': 'NYS', 'name': "Loews Corporation", 'korean_name': "Loews Corporation", 'sector': 'Financials'},
    {'code': 'LOW', 'market': 'NYS', 'name': "Lowe's", 'korean_name': "Lowe's", 'sector': 'Consumer Discretionary'},
    {'code': 'LULU', 'market': 'NAS', 'name': "Lululemon Athletica", 'korean_name': "Lululemon Athletica", 'sector': 'Consumer Discretionary'},
    {'code': 'LYB', 'market': 'NYS', 'name': "LyondellBasell", 'korean_name': "LyondellBasell", 'sector': 'Materials'},
    {'code': 'MTB', 'market': 'NYS', 'name': "M&T Bank", 'korean_name': "M&T Bank", 'sector': 'Financials'},
    {'code': 'MPC', 'market': 'NYS', 'name': "Marathon Petroleum", 'korean_name': "Marathon Petroleum", 'sector': 'Energy'},
    {'code': 'MAR', 'market': 'NYS', 'name': "Marriott International", 'korean_name': "Marriott International", 'sector': 'Consumer Discretionary'},
    {'code': 'MRSH', 'market': 'NAS', 'name': "Marsh McLennan", 'korean_name': "Marsh McLennan", 'sector': 'Financials'},
    {'code': 'MLM', 'market': 'NYS', 'name': "Martin Marietta Materials", 'korean_name': "Martin Marietta Materials", 'sector': 'Materials'},
    {'code': 'MAS', 'market': 'NYS', 'name': "Masco", 'korean_name': "Masco", 'sector': 'Industrials'},
    {'code': 'MA', 'market': 'NYS', 'name': "Mastercard", 'korean_name': "Mastercard", 'sector': 'Financials'},
    {'code': 'MTCH', 'market': 'NAS', 'name': "Match Group", 'korean_name': "Match Group", 'sector': 'Communication Services'},
    {'code': 'MKC', 'market': 'NYS', 'name': "McCormick & Company", 'korean_name': "McCormick & Company", 'sector': 'Consumer Staples'},
    {'code': 'MCD', 'market': 'NYS', 'name': "McDonald's", 'korean_name': "McDonald's", 'sector': 'Consumer Discretionary'},
    {'code': 'MCK', 'market': 'NYS', 'name': "McKesson Corporation", 'korean_name': "McKesson Corporation", 'sector': 'Health Care'},
    {'code': 'MDT', 'market': 'NYS', 'name': "Medtronic", 'korean_name': "Medtronic", 'sector': 'Health Care'},
    {'code': 'MRK', 'market': 'NYS', 'name': "Merck & Co.", 'korean_name': "Merck & Co.", 'sector': 'Health Care'},
    {'code': 'META', 'market': 'NAS', 'name': "Meta Platforms", 'korean_name': "Meta Platforms", 'sector': 'Communication Services'},
    {'code': 'MET', 'market': 'NYS', 'name': "MetLife", 'korean_name': "MetLife", 'sector': 'Financials'},
    {'code': 'MTD', 'market': 'NYS', 'name': "Mettler Toledo", 'korean_name': "Mettler Toledo", 'sector': 'Health Care'},
    {'code': 'MGM', 'market': 'NYS', 'name': "MGM Resorts", 'korean_name': "MGM Resorts", 'sector': 'Consumer Discretionary'},
    {'code': 'MCHP', 'market': 'NAS', 'name': "Microchip Technology", 'korean_name': "Microchip Technology", 'sector': 'Information Technology'},
    {'code': 'MU', 'market': 'NAS', 'name': "Micron Technology", 'korean_name': "Micron Technology", 'sector': 'Information Technology'},
    {'code': 'MSFT', 'market': 'NAS', 'name': "Microsoft", 'korean_name': "Microsoft", 'sector': 'Information Technology'},
    {'code': 'MAA', 'market': 'NYS', 'name': "Mid-America Apartment Communities", 'korean_name': "Mid-America Apartment Communities", 'sector': 'Real Estate'},
    {'code': 'MRNA', 'market': 'NAS', 'name': "Moderna", 'korean_name': "Moderna", 'sector': 'Health Care'},
    {'code': 'MOH', 'market': 'NYS', 'name': "Molina Healthcare", 'korean_name': "Molina Healthcare", 'sector': 'Health Care'},
    {'code': 'TAP', 'market': 'NYS', 'name': "Molson Coors Beverage Company", 'korean_name': "Molson Coors Beverage Company", 'sector': 'Consumer Staples'},
    {'code': 'MDLZ', 'market': 'NAS', 'name': "Mondelez International", 'korean_name': "Mondelez International", 'sector': 'Consumer Staples'},
    {'code': 'MPWR', 'market': 'NAS', 'name': "Monolithic Power Systems", 'korean_name': "Monolithic Power Systems", 'sector': 'Information Technology'},
    {'code': 'MNST', 'market': 'NAS', 'name': "Monster Beverage", 'korean_name': "Monster Beverage", 'sector': 'Consumer Staples'},
    {'code': 'MCO', 'market': 'NYS', 'name': "Moody's Corporation", 'korean_name': "Moody's Corporation", 'sector': 'Financials'},
    {'code': 'MS', 'market': 'NYS', 'name': "Morgan Stanley", 'korean_name': "Morgan Stanley", 'sector': 'Financials'},
    {'code': 'MOS', 'market': 'NYS', 'name': "Mosaic Company (The)", 'korean_name': "Mosaic Company (The)", 'sector': 'Materials'},
    {'code': 'MSI', 'market': 'NYS', 'name': "Motorola Solutions", 'korean_name': "Motorola Solutions", 'sector': 'Information Technology'},
    {'code': 'MSCI', 'market': 'NAS', 'name': "MSCI Inc.", 'korean_name': "MSCI Inc.", 'sector': 'Financials'},
    {'code': 'NDAQ', 'market': 'NAS', 'name': "Nasdaq, Inc.", 'korean_name': "Nasdaq, Inc.", 'sector': 'Financials'},
    {'code': 'NTAP', 'market': 'NAS', 'name': "NetApp", 'korean_name': "NetApp", 'sector': 'Information Technology'},
    {'code': 'NFLX', 'market': 'NAS', 'name': "Netflix", 'korean_name': "Netflix", 'sector': 'Communication Services'},
    {'code': 'NEM', 'market': 'NYS', 'name': "Newmont", 'korean_name': "Newmont", 'sector': 'Materials'},
    {'code': 'NWSA', 'market': 'NAS', 'name': "News Corp (Class A)", 'korean_name': "News Corp (Class A)", 'sector': 'Communication Services'},
    {'code': 'NWS', 'market': 'NYS', 'name': "News Corp (Class B)", 'korean_name': "News Corp (Class B)", 'sector': 'Communication Services'},
    {'code': 'NEE', 'market': 'NYS', 'name': "NextEra Energy", 'korean_name': "NextEra Energy", 'sector': 'Utilities'},
    {'code': 'NKE', 'market': 'NYS', 'name': "Nike, Inc.", 'korean_name': "Nike, Inc.", 'sector': 'Consumer Discretionary'},
    {'code': 'NI', 'market': 'NYS', 'name': "NiSource", 'korean_name': "NiSource", 'sector': 'Utilities'},
    {'code': 'NDSN', 'market': 'NAS', 'name': "Nordson Corporation", 'korean_name': "Nordson Corporation", 'sector': 'Industrials'},
    {'code': 'NSC', 'market': 'NYS', 'name': "Norfolk Southern", 'korean_name': "Norfolk Southern", 'sector': 'Industrials'},
    {'code': 'NTRS', 'market': 'NAS', 'name': "Northern Trust", 'korean_name': "Northern Trust", 'sector': 'Financials'},
    {'code': 'NOC', 'market': 'NYS', 'name': "Northrop Grumman", 'korean_name': "Northrop Grumman", 'sector': 'Industrials'},
    {'code': 'NCLH', 'market': 'NAS', 'name': "Norwegian Cruise Line Holdings", 'korean_name': "Norwegian Cruise Line Holdings", 'sector': 'Consumer Discretionary'},
    {'code': 'NRG', 'market': 'NYS', 'name': "NRG Energy", 'korean_name': "NRG Energy", 'sector': 'Utilities'},
    {'code': 'NUE', 'market': 'NYS', 'name': "Nucor", 'korean_name': "Nucor", 'sector': 'Materials'},
    {'code': 'NVDA', 'market': 'NAS', 'name': "Nvidia", 'korean_name': "Nvidia", 'sector': 'Information Technology'},
    {'code': 'NVR', 'market': 'NYS', 'name': "NVR, Inc.", 'korean_name': "NVR, Inc.", 'sector': 'Consumer Discretionary'},
    {'code': 'NXPI', 'market': 'NAS', 'name': "NXP Semiconductors", 'korean_name': "NXP Semiconductors", 'sector': 'Information Technology'},
    {'code': 'ORLY', 'market': 'NAS', 'name': "O’Reilly Automotive", 'korean_name': "O’Reilly Automotive", 'sector': 'Consumer Discretionary'},
    {'code': 'OXY', 'market': 'NYS', 'name': "Occidental Petroleum", 'korean_name': "Occidental Petroleum", 'sector': 'Energy'},
    {'code': 'ODFL', 'market': 'NAS', 'name': "Old Dominion", 'korean_name': "Old Dominion", 'sector': 'Industrials'},
    {'code': 'OMC', 'market': 'NYS', 'name': "Omnicom Group", 'korean_name': "Omnicom Group", 'sector': 'Communication Services'},
    {'code': 'ON', 'market': 'NYS', 'name': "ON Semiconductor", 'korean_name': "ON Semiconductor", 'sector': 'Information Technology'},
    {'code': 'OKE', 'market': 'NYS', 'name': "Oneok", 'korean_name': "Oneok", 'sector': 'Energy'},
    {'code': 'ORCL', 'market': 'NYS', 'name': "Oracle Corporation", 'korean_name': "Oracle Corporation", 'sector': 'Information Technology'},
    {'code': 'OTIS', 'market': 'NAS', 'name': "Otis Worldwide", 'korean_name': "Otis Worldwide", 'sector': 'Industrials'},
    {'code': 'PCAR', 'market': 'NAS', 'name': "Paccar", 'korean_name': "Paccar", 'sector': 'Industrials'},
    {'code': 'PKG', 'market': 'NYS', 'name': "Packaging Corporation of America", 'korean_name': "Packaging Corporation of America", 'sector': 'Materials'},
    {'code': 'PLTR', 'market': 'NAS', 'name': "Palantir Technologies", 'korean_name': "Palantir Technologies", 'sector': 'Information Technology'},
    {'code': 'PANW', 'market': 'NAS', 'name': "Palo Alto Networks", 'korean_name': "Palo Alto Networks", 'sector': 'Information Technology'},
    {'code': 'PSKY', 'market': 'NAS', 'name': "Paramount Skydance Corporation", 'korean_name': "Paramount Skydance Corporation", 'sector': 'Communication Services'},
    {'code': 'PH', 'market': 'NYS', 'name': "Parker Hannifin", 'korean_name': "Parker Hannifin", 'sector': 'Industrials'},
    {'code': 'PAYX', 'market': 'NAS', 'name': "Paychex", 'korean_name': "Paychex", 'sector': 'Industrials'},
    {'code': 'PAYC', 'market': 'NAS', 'name': "Paycom", 'korean_name': "Paycom", 'sector': 'Industrials'},
    {'code': 'PYPL', 'market': 'NAS', 'name': "PayPal", 'korean_name': "PayPal", 'sector': 'Financials'},
    {'code': 'PNR', 'market': 'NYS', 'name': "Pentair", 'korean_name': "Pentair", 'sector': 'Industrials'},
    {'code': 'PEP', 'market': 'NAS', 'name': "PepsiCo", 'korean_name': "PepsiCo", 'sector': 'Consumer Staples'},
    {'code': 'PFE', 'market': 'NYS', 'name': "Pfizer", 'korean_name': "Pfizer", 'sector': 'Health Care'},
    {'code': 'PCG', 'market': 'NYS', 'name': "PG&E Corporation", 'korean_name': "PG&E Corporation", 'sector': 'Utilities'},
    {'code': 'PM', 'market': 'NYS', 'name': "Philip Morris International", 'korean_name': "Philip Morris International", 'sector': 'Consumer Staples'},
    {'code': 'PSX', 'market': 'NYS', 'name': "Phillips 66", 'korean_name': "Phillips 66", 'sector': 'Energy'},
    {'code': 'PNW', 'market': 'NYS', 'name': "Pinnacle West Capital", 'korean_name': "Pinnacle West Capital", 'sector': 'Utilities'},
    {'code': 'PNC', 'market': 'NYS', 'name': "PNC Financial Services", 'korean_name': "PNC Financial Services", 'sector': 'Financials'},
    {'code': 'POOL', 'market': 'NAS', 'name': "Pool Corporation", 'korean_name': "Pool Corporation", 'sector': 'Consumer Discretionary'},
    {'code': 'PPG', 'market': 'NYS', 'name': "PPG Industries", 'korean_name': "PPG Industries", 'sector': 'Materials'},
    {'code': 'PPL', 'market': 'NYS', 'name': "PPL Corporation", 'korean_name': "PPL Corporation", 'sector': 'Utilities'},
    {'code': 'PFG', 'market': 'NYS', 'name': "Principal Financial Group", 'korean_name': "Principal Financial Group", 'sector': 'Financials'},
    {'code': 'PG', 'market': 'NYS', 'name': "Procter & Gamble", 'korean_name': "Procter & Gamble", 'sector': 'Consumer Staples'},
    {'code': 'PGR', 'market': 'NYS', 'name': "Progressive Corporation", 'korean_name': "Progressive Corporation", 'sector': 'Financials'},
    {'code': 'PLD', 'market': 'NYS', 'name': "Prologis", 'korean_name': "Prologis", 'sector': 'Real Estate'},
    {'code': 'PRU', 'market': 'NYS', 'name': "Prudential Financial", 'korean_name': "Prudential Financial", 'sector': 'Financials'},
    {'code': 'PEG', 'market': 'NYS', 'name': "Public Service Enterprise Group", 'korean_name': "Public Service Enterprise Group", 'sector': 'Utilities'},
    {'code': 'PTC', 'market': 'NYS', 'name': "PTC Inc.", 'korean_name': "PTC Inc.", 'sector': 'Information Technology'},
    {'code': 'PSA', 'market': 'NYS', 'name': "Public Storage", 'korean_name': "Public Storage", 'sector': 'Real Estate'},
    {'code': 'PHM', 'market': 'NYS', 'name': "PulteGroup", 'korean_name': "PulteGroup", 'sector': 'Consumer Discretionary'},
    {'code': 'PWR', 'market': 'NYS', 'name': "Quanta Services", 'korean_name': "Quanta Services", 'sector': 'Industrials'},
    {'code': 'QCOM', 'market': 'NAS', 'name': "Qualcomm", 'korean_name': "Qualcomm", 'sector': 'Information Technology'},
    {'code': 'DGX', 'market': 'NYS', 'name': "Quest Diagnostics", 'korean_name': "Quest Diagnostics", 'sector': 'Health Care'},
    {'code': 'Q', 'market': 'NYS', 'name': "Qnity Electronics", 'korean_name': "Qnity Electronics", 'sector': 'Information Technology'},
    {'code': 'RL', 'market': 'NYS', 'name': "Ralph Lauren Corporation", 'korean_name': "Ralph Lauren Corporation", 'sector': 'Consumer Discretionary'},
    {'code': 'RJF', 'market': 'NYS', 'name': "Raymond James Financial", 'korean_name': "Raymond James Financial", 'sector': 'Financials'},
    {'code': 'RTX', 'market': 'NYS', 'name': "RTX Corporation", 'korean_name': "RTX Corporation", 'sector': 'Industrials'},
    {'code': 'O', 'market': 'NYS', 'name': "Realty Income", 'korean_name': "Realty Income", 'sector': 'Real Estate'},
    {'code': 'REG', 'market': 'NYS', 'name': "Regency Centers", 'korean_name': "Regency Centers", 'sector': 'Real Estate'},
    {'code': 'REGN', 'market': 'NAS', 'name': "Regeneron Pharmaceuticals", 'korean_name': "Regeneron Pharmaceuticals", 'sector': 'Health Care'},
    {'code': 'RF', 'market': 'NYS', 'name': "Regions Financial Corporation", 'korean_name': "Regions Financial Corporation", 'sector': 'Financials'},
    {'code': 'RSG', 'market': 'NYS', 'name': "Republic Services", 'korean_name': "Republic Services", 'sector': 'Industrials'},
    {'code': 'RMD', 'market': 'NYS', 'name': "ResMed", 'korean_name': "ResMed", 'sector': 'Health Care'},
    {'code': 'RVTY', 'market': 'NAS', 'name': "Revvity", 'korean_name': "Revvity", 'sector': 'Health Care'},
    {'code': 'HOOD', 'market': 'NAS', 'name': "Robinhood Markets", 'korean_name': "Robinhood Markets", 'sector': 'Financials'},
    {'code': 'ROK', 'market': 'NYS', 'name': "Rockwell Automation", 'korean_name': "Rockwell Automation", 'sector': 'Industrials'},
    {'code': 'ROL', 'market': 'NYS', 'name': "Rollins, Inc.", 'korean_name': "Rollins, Inc.", 'sector': 'Industrials'},
    {'code': 'ROP', 'market': 'NYS', 'name': "Roper Technologies", 'korean_name': "Roper Technologies", 'sector': 'Information Technology'},
    {'code': 'ROST', 'market': 'NAS', 'name': "Ross Stores", 'korean_name': "Ross Stores", 'sector': 'Consumer Discretionary'},
    {'code': 'RCL', 'market': 'NYS', 'name': "Royal Caribbean Group", 'korean_name': "Royal Caribbean Group", 'sector': 'Consumer Discretionary'},
    {'code': 'SPGI', 'market': 'NAS', 'name': "S&P Global", 'korean_name': "S&P Global", 'sector': 'Financials'},
    {'code': 'CRM', 'market': 'NYS', 'name': "Salesforce", 'korean_name': "Salesforce", 'sector': 'Information Technology'},
    {'code': 'SNDK', 'market': 'NAS', 'name': "Sandisk", 'korean_name': "Sandisk", 'sector': 'Information Technology'},
    {'code': 'SBAC', 'market': 'NAS', 'name': "SBA Communications", 'korean_name': "SBA Communications", 'sector': 'Real Estate'},
    {'code': 'SLB', 'market': 'NYS', 'name': "Schlumberger", 'korean_name': "Schlumberger", 'sector': 'Energy'},
    {'code': 'STX', 'market': 'NYS', 'name': "Seagate Technology", 'korean_name': "Seagate Technology", 'sector': 'Information Technology'},
    {'code': 'SRE', 'market': 'NYS', 'name': "Sempra", 'korean_name': "Sempra", 'sector': 'Utilities'},
    {'code': 'NOW', 'market': 'NYS', 'name': "ServiceNow", 'korean_name': "ServiceNow", 'sector': 'Information Technology'},
    {'code': 'SHW', 'market': 'NYS', 'name': "Sherwin-Williams", 'korean_name': "Sherwin-Williams", 'sector': 'Materials'},
    {'code': 'SPG', 'market': 'NYS', 'name': "Simon Property Group", 'korean_name': "Simon Property Group", 'sector': 'Real Estate'},
    {'code': 'SWKS', 'market': 'NAS', 'name': "Skyworks Solutions", 'korean_name': "Skyworks Solutions", 'sector': 'Information Technology'},
    {'code': 'SJM', 'market': 'NYS', 'name': "J.M. Smucker Company (The)", 'korean_name': "J.M. Smucker Company (The)", 'sector': 'Consumer Staples'},
    {'code': 'SW', 'market': 'NYS', 'name': "Smurfit Westrock", 'korean_name': "Smurfit Westrock", 'sector': 'Materials'},
    {'code': 'SNA', 'market': 'NYS', 'name': "Snap-on", 'korean_name': "Snap-on", 'sector': 'Industrials'},
    {'code': 'SOLV', 'market': 'NAS', 'name': "Solventum", 'korean_name': "Solventum", 'sector': 'Health Care'},
    {'code': 'SO', 'market': 'NYS', 'name': "Southern Company", 'korean_name': "Southern Company", 'sector': 'Utilities'},
    {'code': 'LUV', 'market': 'NYS', 'name': "Southwest Airlines", 'korean_name': "Southwest Airlines", 'sector': 'Industrials'},
    {'code': 'SWK', 'market': 'NYS', 'name': "Stanley Black & Decker", 'korean_name': "Stanley Black & Decker", 'sector': 'Industrials'},
    {'code': 'SBUX', 'market': 'NAS', 'name': "Starbucks", 'korean_name': "Starbucks", 'sector': 'Consumer Discretionary'},
    {'code': 'STT', 'market': 'NYS', 'name': "State Street Corporation", 'korean_name': "State Street Corporation", 'sector': 'Financials'},
    {'code': 'STLD', 'market': 'NAS', 'name': "Steel Dynamics", 'korean_name': "Steel Dynamics", 'sector': 'Materials'},
    {'code': 'STE', 'market': 'NYS', 'name': "Steris", 'korean_name': "Steris", 'sector': 'Health Care'},
    {'code': 'SYK', 'market': 'NYS', 'name': "Stryker Corporation", 'korean_name': "Stryker Corporation", 'sector': 'Health Care'},
    {'code': 'SMCI', 'market': 'NAS', 'name': "Supermicro", 'korean_name': "Supermicro", 'sector': 'Information Technology'},
    {'code': 'SYF', 'market': 'NYS', 'name': "Synchrony Financial", 'korean_name': "Synchrony Financial", 'sector': 'Financials'},
    {'code': 'SNPS', 'market': 'NAS', 'name': "Synopsys", 'korean_name': "Synopsys", 'sector': 'Information Technology'},
    {'code': 'SYY', 'market': 'NYS', 'name': "Sysco", 'korean_name': "Sysco", 'sector': 'Consumer Staples'},
    {'code': 'TMUS', 'market': 'NAS', 'name': "T-Mobile US", 'korean_name': "T-Mobile US", 'sector': 'Communication Services'},
    {'code': 'TROW', 'market': 'NAS', 'name': "T. Rowe Price", 'korean_name': "T. Rowe Price", 'sector': 'Financials'},
    {'code': 'TTWO', 'market': 'NAS', 'name': "Take-Two Interactive", 'korean_name': "Take-Two Interactive", 'sector': 'Communication Services'},
    {'code': 'TPR', 'market': 'NYS', 'name': "Tapestry, Inc.", 'korean_name': "Tapestry, Inc.", 'sector': 'Consumer Discretionary'},
    {'code': 'TRGP', 'market': 'NAS', 'name': "Targa Resources", 'korean_name': "Targa Resources", 'sector': 'Energy'},
    {'code': 'TGT', 'market': 'NYS', 'name': "Target Corporation", 'korean_name': "Target Corporation", 'sector': 'Consumer Staples'},
    {'code': 'TEL', 'market': 'NYS', 'name': "TE Connectivity", 'korean_name': "TE Connectivity", 'sector': 'Information Technology'},
    {'code': 'TDY', 'market': 'NYS', 'name': "Teledyne Technologies", 'korean_name': "Teledyne Technologies", 'sector': 'Information Technology'},
    {'code': 'TER', 'market': 'NYS', 'name': "Teradyne", 'korean_name': "Teradyne", 'sector': 'Information Technology'},
    {'code': 'TSLA', 'market': 'NAS', 'name': "Tesla, Inc.", 'korean_name': "Tesla, Inc.", 'sector': 'Consumer Discretionary'},
    {'code': 'TXN', 'market': 'NAS', 'name': "Texas Instruments", 'korean_name': "Texas Instruments", 'sector': 'Information Technology'},
    {'code': 'TPL', 'market': 'NYS', 'name': "Texas Pacific Land Corporation", 'korean_name': "Texas Pacific Land Corporation", 'sector': 'Energy'},
    {'code': 'TXT', 'market': 'NYS', 'name': "Textron", 'korean_name': "Textron", 'sector': 'Industrials'},
    {'code': 'TMO', 'market': 'NYS', 'name': "Thermo Fisher Scientific", 'korean_name': "Thermo Fisher Scientific", 'sector': 'Health Care'},
    {'code': 'TJX', 'market': 'NYS', 'name': "TJX Companies", 'korean_name': "TJX Companies", 'sector': 'Consumer Discretionary'},
    {'code': 'TKO', 'market': 'NYS', 'name': "TKO Group Holdings", 'korean_name': "TKO Group Holdings", 'sector': 'Communication Services'},
    {'code': 'TTD', 'market': 'NYS', 'name': "Trade Desk (The)", 'korean_name': "Trade Desk (The)", 'sector': 'Communication Services'},
    {'code': 'TSCO', 'market': 'NAS', 'name': "Tractor Supply", 'korean_name': "Tractor Supply", 'sector': 'Consumer Discretionary'},
    {'code': 'TT', 'market': 'NYS', 'name': "Trane Technologies", 'korean_name': "Trane Technologies", 'sector': 'Industrials'},
    {'code': 'TDG', 'market': 'NYS', 'name': "TransDigm Group", 'korean_name': "TransDigm Group", 'sector': 'Industrials'},
    {'code': 'TRV', 'market': 'NYS', 'name': "Travelers Companies (The)", 'korean_name': "Travelers Companies (The)", 'sector': 'Financials'},
    {'code': 'TRMB', 'market': 'NAS', 'name': "Trimble Inc.", 'korean_name': "Trimble Inc.", 'sector': 'Information Technology'},
    {'code': 'TFC', 'market': 'NYS', 'name': "Truist Financial", 'korean_name': "Truist Financial", 'sector': 'Financials'},
    {'code': 'TYL', 'market': 'NYS', 'name': "Tyler Technologies", 'korean_name': "Tyler Technologies", 'sector': 'Information Technology'},
    {'code': 'TSN', 'market': 'NYS', 'name': "Tyson Foods", 'korean_name': "Tyson Foods", 'sector': 'Consumer Staples'},
    {'code': 'USB', 'market': 'NYS', 'name': "U.S. Bancorp", 'korean_name': "U.S. Bancorp", 'sector': 'Financials'},
    {'code': 'UBER', 'market': 'NAS', 'name': "Uber", 'korean_name': "Uber", 'sector': 'Industrials'},
    {'code': 'UDR', 'market': 'NYS', 'name': "UDR, Inc.", 'korean_name': "UDR, Inc.", 'sector': 'Real Estate'},
    {'code': 'ULTA', 'market': 'NAS', 'name': "Ulta Beauty", 'korean_name': "Ulta Beauty", 'sector': 'Consumer Discretionary'},
    {'code': 'UNP', 'market': 'NYS', 'name': "Union Pacific Corporation", 'korean_name': "Union Pacific Corporation", 'sector': 'Industrials'},
    {'code': 'UAL', 'market': 'NYS', 'name': "United Airlines Holdings", 'korean_name': "United Airlines Holdings", 'sector': 'Industrials'},
    {'code': 'UPS', 'market': 'NYS', 'name': "United Parcel Service", 'korean_name': "United Parcel Service", 'sector': 'Industrials'},
    {'code': 'URI', 'market': 'NYS', 'name': "United Rentals", 'korean_name': "United Rentals", 'sector': 'Industrials'},
    {'code': 'UNH', 'market': 'NYS', 'name': "UnitedHealth Group", 'korean_name': "UnitedHealth Group", 'sector': 'Health Care'},
    {'code': 'UHS', 'market': 'NYS', 'name': "Universal Health Services", 'korean_name': "Universal Health Services", 'sector': 'Health Care'},
    {'code': 'VLO', 'market': 'NYS', 'name': "Valero Energy", 'korean_name': "Valero Energy", 'sector': 'Energy'},
    {'code': 'VTR', 'market': 'NYS', 'name': "Ventas", 'korean_name': "Ventas", 'sector': 'Real Estate'},
    {'code': 'VLTO', 'market': 'NAS', 'name': "Veralto", 'korean_name': "Veralto", 'sector': 'Industrials'},
    {'code': 'VRSN', 'market': 'NAS', 'name': "Verisign", 'korean_name': "Verisign", 'sector': 'Information Technology'},
    {'code': 'VRSK', 'market': 'NAS', 'name': "Verisk Analytics", 'korean_name': "Verisk Analytics", 'sector': 'Industrials'},
    {'code': 'VZ', 'market': 'NYS', 'name': "Verizon", 'korean_name': "Verizon", 'sector': 'Communication Services'},
    {'code': 'VRTX', 'market': 'NAS', 'name': "Vertex Pharmaceuticals", 'korean_name': "Vertex Pharmaceuticals", 'sector': 'Health Care'},
    {'code': 'VTRS', 'market': 'NAS', 'name': "Viatris", 'korean_name': "Viatris", 'sector': 'Health Care'},
    {'code': 'VICI', 'market': 'NAS', 'name': "Vici Properties", 'korean_name': "Vici Properties", 'sector': 'Real Estate'},
    {'code': 'V', 'market': 'NYS', 'name': "Visa Inc.", 'korean_name': "Visa Inc.", 'sector': 'Financials'},
    {'code': 'VST', 'market': 'NYS', 'name': "Vistra Corp.", 'korean_name': "Vistra Corp.", 'sector': 'Utilities'},
    {'code': 'VMC', 'market': 'NYS', 'name': "Vulcan Materials Company", 'korean_name': "Vulcan Materials Company", 'sector': 'Materials'},
    {'code': 'WRB', 'market': 'NYS', 'name': "W. R. Berkley Corporation", 'korean_name': "W. R. Berkley Corporation", 'sector': 'Financials'},
    {'code': 'GWW', 'market': 'NYS', 'name': "W. W. Grainger", 'korean_name': "W. W. Grainger", 'sector': 'Industrials'},
    {'code': 'WAB', 'market': 'NYS', 'name': "Wabtec", 'korean_name': "Wabtec", 'sector': 'Industrials'},
    {'code': 'WMT', 'market': 'NYS', 'name': "Walmart", 'korean_name': "Walmart", 'sector': 'Consumer Staples'},
    {'code': 'DIS', 'market': 'NYS', 'name': "Walt Disney Company (The)", 'korean_name': "Walt Disney Company (The)", 'sector': 'Communication Services'},
    {'code': 'WBD', 'market': 'NYS', 'name': "Warner Bros. Discovery", 'korean_name': "Warner Bros. Discovery", 'sector': 'Communication Services'},
    {'code': 'WM', 'market': 'NYS', 'name': "Waste Management", 'korean_name': "Waste Management", 'sector': 'Industrials'},
    {'code': 'WAT', 'market': 'NYS', 'name': "Waters Corporation", 'korean_name': "Waters Corporation", 'sector': 'Health Care'},
    {'code': 'WEC', 'market': 'NYS', 'name': "WEC Energy Group", 'korean_name': "WEC Energy Group", 'sector': 'Utilities'},
    {'code': 'WFC', 'market': 'NYS', 'name': "Wells Fargo", 'korean_name': "Wells Fargo", 'sector': 'Financials'},
    {'code': 'WELL', 'market': 'NAS', 'name': "Welltower", 'korean_name': "Welltower", 'sector': 'Real Estate'},
    {'code': 'WST', 'market': 'NYS', 'name': "West Pharmaceutical Services", 'korean_name': "West Pharmaceutical Services", 'sector': 'Health Care'},
    {'code': 'WDC', 'market': 'NYS', 'name': "Western Digital", 'korean_name': "Western Digital", 'sector': 'Information Technology'},
    {'code': 'WY', 'market': 'NYS', 'name': "Weyerhaeuser", 'korean_name': "Weyerhaeuser", 'sector': 'Real Estate'},
    {'code': 'WSM', 'market': 'NYS', 'name': "Williams-Sonoma, Inc.", 'korean_name': "Williams-Sonoma, Inc.", 'sector': 'Consumer Discretionary'},
    {'code': 'WMB', 'market': 'NYS', 'name': "Williams Companies", 'korean_name': "Williams Companies", 'sector': 'Energy'},
    {'code': 'WTW', 'market': 'NYS', 'name': "Willis Towers Watson", 'korean_name': "Willis Towers Watson", 'sector': 'Financials'},
    {'code': 'WDAY', 'market': 'NAS', 'name': "Workday, Inc.", 'korean_name': "Workday, Inc.", 'sector': 'Information Technology'},
    {'code': 'WYNN', 'market': 'NAS', 'name': "Wynn Resorts", 'korean_name': "Wynn Resorts", 'sector': 'Consumer Discretionary'},
    {'code': 'XEL', 'market': 'NYS', 'name': "Xcel Energy", 'korean_name': "Xcel Energy", 'sector': 'Utilities'},
    {'code': 'XYL', 'market': 'NYS', 'name': "Xylem Inc.", 'korean_name': "Xylem Inc.", 'sector': 'Industrials'},
    {'code': 'YUM', 'market': 'NYS', 'name': "Yum! Brands", 'korean_name': "Yum! Brands", 'sector': 'Consumer Discretionary'},
    {'code': 'ZBRA', 'market': 'NAS', 'name': "Zebra Technologies", 'korean_name': "Zebra Technologies", 'sector': 'Information Technology'},
    {'code': 'ZBH', 'market': 'NYS', 'name': "Zimmer Biomet", 'korean_name': "Zimmer Biomet", 'sector': 'Health Care'},
    {'code': 'ZTS', 'market': 'NYS', 'name': "Zoetis", 'korean_name': "Zoetis", 'sector': 'Health Care'},
]
